name: CI
# Relevant to events - https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows
on:
  push:
    branch: master
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review, review_requested ]
    paths:
    - 'src/**'
    - 'Cargo.toml'
env:
  CLICOLOR_FORCE: 1
jobs:
  ci:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta, nightly, 1.40.0]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        profile: minimal
        override: true
    - name: Install cargo-make
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: --debug cargo-make
    - name: Run CI
      if: matrix.rust == 'stable' || matrix.rust == 'beta'
      uses: actions-rs/cargo@v1
      with:
        command: run
        args: --bin cargo-make --target-dir target/ci -- make ci-flow
    - name: Run CI (Allow Failures)
      if: matrix.rust == 'nightly'
      continue-on-error: true
      uses: actions-rs/cargo@v1
      with:
        command: run
        args: --bin cargo-make --target-dir target/ci -- make ci-flow
    - name: Run CI (Minimal Supported Rust Version)
      if: matrix.rust != 'stable' && matrix.rust != 'beta' && matrix.rust != 'nightly'
      uses: actions-rs/cargo@v1
      with:
        command: make
        args: ci-flow
